OdeToFood/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OdeToFood.Data;
using OdeToFood.Models;

namespace OdeToFood.Controllers
{
	[Authorize]
	public class RestaurantsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public RestaurantsController(ApplicationDbContext context)
		{
			_context = context;
		}

		[AllowAnonymous]
		public async Task<IActionResult> Index()
		{
			return View(await _context.Restaurants.ToListAsync());
		}

		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var restaurant = await _context.Restaurants
							.FirstOrDefaultAsync(m => m.Id == id);
			if (restaurant == null)
			{
				return NotFound();
			}

			return View(restaurant);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,City,Country")] Restaurant restaurant)
		{
			if (ModelState.IsValid)
			{
				_context.Add(restaurant);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(restaurant);
		}

		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var restaurant = await _context.Restaurants.FindAsync(id);
			if (restaurant == null)
			{
				return NotFound();
			}
			return View(restaurant);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,City,Country")] Restaurant restaurant)
		{
			if (id != restaurant.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(restaurant);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!RestaurantExists(restaurant.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(restaurant);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var restaurant = await _context.Restaurants
							.FirstOrDefaultAsync(m => m.Id == id);
			if (restaurant == null)
			{
				return NotFound();
			}

			return View(restaurant);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var restaurant = await _context.Restaurants.FindAsync(id);
			_context.Restaurants.Remove(restaurant);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool RestaurantExists(int id)
		{
			return _context.Restaurants.Any(e => e.Id == id);
		}
	}
}

OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/pagedList.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light orange border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="food-picture" src="~/img/food.jpg"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderSection("Featured", required: false)
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        @*<div>@await Component.InvokeAsync("BestReview")</div>*@
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OdeToFood - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @Html.RenderUnobtrusiveAjaxScript()
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OdeToFood/Views/Shared/_review.cshtml
@model OdeToFood.Models.RestaurantReview
@*<div class="review">
        <h4>@Model.Name</h4>
        <span>@Model.Rating</span>
        <p>@Model.City, @Model.Country</p>
        <span class="right">@Html.ActionLink("Edit", "Edit", new { id = Model.Id })</span>
    </div>*@